# Mandatory settings

name: Notes from a coder
paginate: 2
url: albertorocha.me # add your site url (format: http://example.com/)
description: description
blog_theme: light # Or use dark

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: notesfromacoder
ga_analytics: UA-96604674-1
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: betogrun # Add your GitHub handle
  linkedin: betogrun # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: betogrun@gmail.com # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: "/posts/page/:num/"
permalink: posts/:slug
