source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'html-proofer'
gem 'image_optim'
gem 'jekyll', '3.9.3'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'kramdown-parser-gfm'
gem 'mini_magick'
gem 'sass'
gem 'sprockets', '~> 3.7'
gem 'uglifier'
